export const requests = {
  trending: "/trending/all/week",
  topRatedMovies: "/movie/top_rated",
  actionMovies: "/discover/movie?with_genres=28",
  comedyMovies: "/discover/movie?with_genres=35",
  horrorMovies: "/discover/movie?with_genres=27",
  romanceMovies: "/discover/movie?with_genres=10749",
  nowPlaying: "/movie/now_playing",
  popularMovies: "/movie/popular",
  popularShows: "/tv/popular",
  animeShows: "/discover/tv?with_genres=16",
  // New TV specific
  trendingShows: "/trending/tv/week",
  topRatedShows: "/tv/top_rated",
  tvDramas: "/discover/tv?with_genres=18",
  tvComedies: "/discover/tv?with_genres=35",
  tvCrimes: "/discover/tv?with_genres=80",
  tvSciFi: "/discover/tv?with_genres=10765",
  tvReality: "/discover/tv?with_genres=10764",
  tvFamily: "/discover/tv?with_genres=10751",
  tvKids: "/discover/tv?with_genres=10762",
  tvAction: "/discover/tv?with_genres=10759",
  tvMystery: "/discover/tv?with_genres=9648",
  kDramas: "/discover/tv?with_origin_country=KR",
  britishShows: "/discover/tv?with_origin_country=GB",
  // Movies
  bollywoodMovies: "/discover/movie?with_original_language=hi",
  indianMovies: "/discover/movie?region=IN&sort_by=popularity.desc",
  usMovies: "/discover/movie?with_origin_country=US",
  koreanMovies: "/discover/movie?with_origin_country=KR",
  europeanMovies: "/discover/movie?with_origin_country=FR",
  thrillerMovies: "/discover/movie?with_genres=53",
  sciFiMovies: "/discover/movie?with_genres=878",
  animationMovies: "/discover/movie?with_genres=16",
  documentaries: "/discover/movie?with_genres=99",
  awardWinning: "/discover/movie?sort_by=vote_average.desc&vote_count.gte=1000",
  familyMovies: "/discover/movie?with_genres=10751",
  crimeMovies: "/discover/movie?with_genres=80",
  dramaMovies: "/discover/movie?with_genres=18",

  newOnNetflix: "/movie/now_playing",
  top10Movies: "/trending/movie/day",
  top10Shows: "/trending/tv/day",
  comingSoon: "/movie/upcoming",
  popularThisWeek: "/trending/all/week",
};

export const getMovieVideos = (id, mediaType = "movie") =>
  `/${mediaType}/${id}/videos`;
